# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-31 23:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_man', models.GenericIPAddressField(auto_created=True, verbose_name='\u521b\u5efa\u4eba')),
                ('comment', models.TextField(verbose_name='\u8bc4\u8bba')),
                ('grade', models.IntegerField(default=0, verbose_name='\u8bc4\u5206')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'ordering': ['comment'],
                'verbose_name': '\u8bc4\u8bba',
                'verbose_name_plural': '\u8bc4\u8bba',
            },
        ),
        migrations.CreateModel(
            name='ErrorRe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ErrorRes', models.CharField(max_length=255, verbose_name='\u6b63\u5219\u8868\u8fbe\u5f0f')),
            ],
            options={
                'ordering': ['-ErrorRes'],
                'verbose_name': '\u6b63\u5219\u5b58\u50a8\u8868',
                'verbose_name_plural': '\u6b63\u5219\u5b58\u50a8\u8868',
            },
        ),
        migrations.CreateModel(
            name='ErrorSelfFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ErrorSelfFile', models.ImageField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='FileList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u540d\u5b57')),
                ('path', models.CharField(max_length=255, verbose_name='\u6587\u4ef6\u8def\u5f84')),
                ('tat', models.CharField(max_length=255, verbose_name='\u6240\u5c5e\u57df')),
            ],
            options={
                'verbose_name': '\u6587\u4ef6\u5217\u8868',
                'verbose_name_plural': '\u6587\u4ef6\u5217\u8868',
            },
        ),
        migrations.AddField(
            model_name='errorselffile',
            name='fileId',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='upgrade.FileList', verbose_name='__'),
        ),
        migrations.AddField(
            model_name='errorre',
            name='fileId',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='upgrade.FileList', verbose_name='\u6587\u4ef6\u5217\u8868'),
        ),
        migrations.AddField(
            model_name='comment',
            name='ErrorRe',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='upgrade.ErrorRe', verbose_name='\u6b63\u5219\u8868\u8fbe\u8bd5'),
        ),
    ]
